const $=s=>document.querySelector(s);let logged=false,before=null,lastEvent=null,imageURL=null,reading=false,panelKey=null,loadedOlder=false;
async function api(path,data){const r=await fetch(path,{method:data===undefined?'GET':'POST',headers:data===undefined?{}:{'Content-Type':'application/json'},body:data===undefined?undefined:JSON.stringify(data)});const b=await r.json();if(!r.ok){if(r.status===401){logged=false;$('#workspace').hidden=true;$('#login').hidden=false}throw Error(b.error||'请求失败')}return b}
const error=e=>{$('#error').textContent=e.message};
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();try{await api('/v1/login',{password:$('#password').value});$('#password').value='';await update()}catch(e){error(e)}});
async function update(){try{const s=await api('/v1/state');logged=true;$('#workspace').hidden=false;$('#login').hidden=true;$('#identity').textContent=s.identity.building+' · '+s.identity.unit;renderPanels(s.panels);$('#clock').textContent=new Date(s.time*1000).toLocaleTimeString('zh-CN',{hour12:false});$('#clockSource').textContent=(s.clock.synchronized?'已对时 · ':'未同步 · ')+(s.clock.source==='dhcp'?'DHCP NTP':'公共 NTP');$('#network').textContent=s.network==='ready'?'门禁网络已连接':'等待门禁网络';$('#callState').textContent=({idle:'等待来访',ringing:'正在连接',early_video:'视频已接通',audio:'通话中',ending:'正在挂断'}[s.call]||s.call)+(s.panel?' · '+s.panel:'');$('#notice').textContent=s.notice;$('#autoState').textContent=s.auto.enabled?(s.auto.minutes===0?'已启用 · 无时限':'已启用 · 至 '+new Date(s.auto.expires_at*1000).toLocaleString('zh-CN')):'已关闭';$('#open').disabled=!s.allow_open||!s.relays.length||!['early_video','audio'].includes(s.call);$('#answer').disabled=!s.audio_available||s.call!=='early_video';$('#hangup').disabled=!['ringing','early_video','audio'].includes(s.call);document.querySelectorAll('[data-action=preview]').forEach(b=>b.disabled=s.network!=='ready'||s.call!=='idle');if(!loadedOlder&&s.events[0]?.id!==lastEvent){lastEvent=s.events[0]?.id;await logs(false)}if(s.video_ready){await frame()}else{$('#video').hidden=true;$('#videoHint').hidden=false}}catch(e){if(logged)error(e)}}
async function frame(){if(reading)return;reading=true;try{const r=await fetch('/v1/frame.jpg');if(r.ok){const next=URL.createObjectURL(await r.blob());$('#video').src=next;$('#video').hidden=false;$('#videoHint').hidden=true;if(imageURL)URL.revokeObjectURL(imageURL);imageURL=next}}finally{reading=false}}
async function control(button){button.disabled=true;try{await api('/v1/control',{action:button.dataset.action,panel:button.dataset.panel||null,request_id:crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random()});await update()}catch(e){error(e)}finally{setTimeout(update,500)}}
document.querySelectorAll('[data-action]').forEach(b=>b.addEventListener('click',()=>control(b)));
function renderPanels(panels){const key=JSON.stringify(panels);if(key===panelKey)return;panelKey=key;$('#panelButtons').replaceChildren();for(const panel of panels){const b=document.createElement('button');b.textContent=panel.name;b.dataset.action='preview';b.dataset.panel=panel.id;b.addEventListener('click',()=>control(b));$('#panelButtons').append(b)}}
$('#enableAuto').addEventListener('click',()=>api('/v1/auto',{minutes:Number($('#duration').value)}).then(update).catch(error));$('#disableAuto').addEventListener('click',()=>api('/v1/auto',{minutes:null}).then(update).catch(error));$('#logout').addEventListener('click',()=>api('/v1/logout',{}).then(()=>{logged=false;$('#workspace').hidden=true;$('#login').hidden=false}).catch(error));
async function logs(older){loadedOlder=older;const q=new URLSearchParams({limit:'50',kind:$('#kind').value});if(older&&before)q.set('before',before);const result=await api('/v1/logs?'+q);if(!older)$('#events').replaceChildren();for(const e of result.events){const tr=document.createElement('tr');for(const value of [new Date(e.time*1000).toLocaleString('zh-CN'),e.text]){const td=document.createElement('td');td.textContent=value;tr.append(td)}const td=document.createElement('td'),details=document.createElement('details'),summary=document.createElement('summary'),pre=document.createElement('pre');summary.textContent=e.kind;pre.textContent=JSON.stringify(e.detail,null,2);details.append(summary,pre);td.append(details);tr.append(td);$('#events').append(tr)}before=result.next_before;$('#older').disabled=result.events.length<50}
$('#older').addEventListener('click',()=>logs(true).catch(error));$('#refreshLogs').addEventListener('click',()=>logs(false).catch(error));$('#kind').addEventListener('change',()=>logs(false).catch(error));update();setInterval(()=>{if(logged)update()},1500);
